---
title: "Groundhog Leaderboard"
#output: html_document
output:
  flexdashboard::flex_dashboard
css: ../styling/styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r}
library(flexdashboard)
library(bslib)

```

```{r}
library(tidyverse)
library(reactable)
library(reactablefmtr)
library(htmltools)
library(scales)

# pull in raw data 
groundhogs_raw <- read_csv('../data/groundhogs_2025.csv')
predictions_raw <- read_csv('../data/predictions_2025.csv')
avg_daily_temp_df <- read_csv('../data/average_daily_temp_2025.csv')
```

### {#leaderboard}

```{r}
# data frame with average winter temp (6 weeks preceding groundhog day)
avg_winter_temp_df <- avg_daily_temp_df %>% 
  filter(DOY %in% c(1:33, 357:366)) %>% 
  mutate(groundhog_winter_year = if_else(DOY %in% c(357:366), YEAR + 1, YEAR)) %>% 
  group_by(id, groundhog_winter_year) %>% 
  summarise(avg_winter_temp = mean(T2M))

# data frame with average temp for prediction interval (6 weeks following groundhog day)
avg_prediction_temp_df <- avg_daily_temp_df %>% 
  filter(DOY %in% c(34:75)) %>% 
  group_by(id, YEAR) %>% 
  summarise(avg_prediction_temp = mean(T2M))

# data frame with average spring temp (6 weeks following prediction interval -- 6-12 weeks following groundhog day)
avg_spring_temp_df <- avg_daily_temp_df %>% 
  filter(DOY %in% c(75:116)) %>% 
  group_by(id, YEAR) %>% 
  summarise(avg_spring_temp = mean(T2M))
  
# join dataframes together, then compare which season prediction interval is closest to 
prediction_eval_df <- predictions_raw %>% 
  filter(year > 1980) %>% 
  filter(!is.na(shadow)) %>% 
  left_join(avg_winter_temp_df, by = c('id', 'year' = 'groundhog_winter_year')) %>% 
  left_join(avg_prediction_temp_df, by = c('id', 'year' = 'YEAR')) %>% 
  left_join(avg_spring_temp_df, by = c('id', 'year' = 'YEAR')) %>% 
  mutate(delta_winter = abs(avg_winter_temp - avg_prediction_temp)) %>% 
  mutate(delta_spring = abs(avg_spring_temp - avg_prediction_temp)) %>% 
  mutate(six_more_weeks = delta_winter < delta_spring) %>% 
  mutate(is_correct = if_else(shadow & six_more_weeks, TRUE, FALSE))

# make a separate leaderboard dataframe, compute accuracy 
leaderboard_df <- prediction_eval_df %>% 
  group_by(id) %>% 
  summarize(num_predictions = n(), 
            total_correct = sum(is_correct),
            accuracy = sum(is_correct)/n(),
            start_year = min(year)) %>% 
  arrange(desc(accuracy)) %>% 
  mutate(rank = row_number()) %>% 
  left_join(groundhogs_raw, by = 'id') 
  
# use reactable to make interactive leaderboard 
leaderboard_df %>% 
  select(rank, name, accuracy, type, city, region, country) %>%
  reactable(theme = fivethirtyeight(),
            defaultColDef = colDef(align = "center",
                                   headerStyle = list(background = "#565A0480",
                                                      fontSize = "15px")),
            columns = list(name = colDef(name = 'Name',
                                         cell = function(value, index) {
                                           url <- leaderboard_df$source[index]
                                           tags$a(href = url, value)
                                         }),
                           accuracy = colDef(name = "Accuracy",
                                                 cell = data_bars(., text_position = 'above',
                                                                  number_fmt = percent_format(accuracy = 0.1),
                                                                  fill_color = '#8A1A6B', background = '#EFD6C1')),
                           region = colDef(name = "State/Province",
                                           width = 150),
                           rank = colDef(minWidth = 50),
                           url = colDef(show = FALSE)),
            onClick = 'expand',
            details = function(index){
              
              sub_table <- leaderboard_df %>% 
                slice(index) %>% 
                select(image, description, num_predictions, start_year, source) 
              
              reactable(sub_table,
                        style = list(opacity = 0.99),
                        defaultColDef = colDef(headerVAlign = 'bottom',
                                               headerStyle = list(background = "#FFFFFF80",
                                                                  textAlign = "left",
                                                                  overflowWrap = "normal")),
                        columns = list(image = colDef(name = 'Photo',
                                                      cell = function(value) {
                                                        tags$img(src = value,
                                                                 width = 300)
                                                        },
                                                      width = 320),
                                       description = colDef(name = "Description",
                                                            minWidth = 240,
                                                            cell = function(value, index) {
                                                              url <- sub_table$source[index]
                                                              tagList(value, tags$br(), tags$br(), tags$a("Source", href = url))}),
                                       num_predictions = colDef(name = "Total Predictions",
                                                                minWidth = 90,
                                                                align = "left"),
                                       start_year = colDef(name = "First Year Prognosticating",
                                                           minWidth = 120,
                                                           align = "left"),
                                       source = colDef(show = FALSE)))
            },
            highlight = TRUE,
            defaultPageSize = 15,
            filterable = TRUE,
            searchable = TRUE,
            class = "leaderboard-rt",
            rowClass = "my-row") %>% 
  add_title("Groundhog Leaderboard", font_size = 30) %>% 
  add_subtitle("Prognosticator Ranks by Overall Weather Prediction Accuracy", font_size = 20, font_color = 'darkgrey')
```
